import type { Dispatch, SetStateAction } from 'react';
import {
  addDependenciesToCanvas,
  addEntitiesToCanvas,
  addEntityToCanvas,
  addPrimaryEntitiesForScope,
  addScopeToCanvas,
  applySelectedViewpoint,
  arrangeAllCanvasNodesInteractive,
  arrangeCanvasAroundFocus,
  arrangeCanvasNodesInteractivelyWithMode,
  clearCanvas,
  focusBrowserElement,
  isolateCanvasSelection,
  moveCanvasNode,
  openFactsPanel,
  openSnapshotSession,
  panCanvasViewport,
  relayoutCanvas,
  removeCanvasSelection,
  removeEntityFromCanvas,
  requestFitCanvasView,
  selectBrowserScope,
  selectCanvasEntity,
  setBrowserSearch,
  setBrowserTreeMode,
  setCanvasViewport,
  setSelectedViewpoint,
  setViewpointApplyMode,
  setViewpointPresentationPreference,
  setViewpointScopeMode,
  setViewpointVariant,
  toggleCanvasNodePin,
  type BrowserSessionState,
} from '../browserSessionStore';
import type { BrowserSessionActionGroups } from './browserSession.types';

export function createBrowserSessionActionGroups(
  setState: Dispatch<SetStateAction<BrowserSessionState>>,
): BrowserSessionActionGroups {
  return {
    lifecycle: {
      openSnapshotSession: (options) => setState((current) => openSnapshotSession(current, options)),
      replaceState: (nextState) => setState(nextState),
    },
    navigation: {
      selectScope: (scopeId) => setState((current) => selectBrowserScope(current, scopeId)),
      setSearch: (query, scopeId) => setState((current) => setBrowserSearch(current, query, scopeId)),
      setTreeMode: (treeMode) => setState((current) => setBrowserTreeMode(current, treeMode)),
    },
    viewpoint: {
      setSelectedViewpoint: (viewpointId) => setState((current) => setSelectedViewpoint(current, viewpointId)),
      setScopeMode: (scopeMode) => setState((current) => setViewpointScopeMode(current, scopeMode)),
      setApplyMode: (applyMode) => setState((current) => setViewpointApplyMode(current, applyMode)),
      setVariant: (variant) => setState((current) => setViewpointVariant(current, variant)),
      setPresentationPreference: (preference) => setState((current) => setViewpointPresentationPreference(current, preference)),
      applySelectedViewpoint: () => setState((current) => applySelectedViewpoint(current)),
    },
    canvas: {
      addScopeToCanvas: (scopeId) => setState((current) => addScopeToCanvas(current, scopeId)),
      addEntityToCanvas: (entityId) => setState((current) => addEntityToCanvas(current, entityId)),
      addEntitiesToCanvas: (entityIds) => setState((current) => addEntitiesToCanvas(current, entityIds)),
      addPrimaryEntitiesForScope: (scopeId) => setState((current) => addPrimaryEntitiesForScope(current, scopeId)),
      selectEntity: (entityId, additive) => setState((current) => selectCanvasEntity(current, entityId, additive)),
      addDependenciesToCanvas: (entityId, direction) => setState((current) => addDependenciesToCanvas(current, entityId, direction)),
      removeEntityFromCanvas: (entityId) => setState((current) => removeEntityFromCanvas(current, entityId)),
      isolateSelection: () => setState((current) => isolateCanvasSelection(current)),
      removeSelection: () => setState((current) => removeCanvasSelection(current)),
      toggleNodePin: (node) => setState((current) => toggleCanvasNodePin(current, node)),
      moveNode: (node, position) => setState((current) => moveCanvasNode(current, node, position)),
      setViewport: (viewport) => setState((current) => setCanvasViewport(current, viewport)),
      panViewport: (delta) => setState((current) => panCanvasViewport(current, delta)),
      arrangeAllNodes: () => setState((current) => arrangeAllCanvasNodesInteractive(current)),
      arrangeWithMode: (mode) => setState((current) => arrangeCanvasNodesInteractivelyWithMode(current, mode)),
      arrangeAroundFocus: () => setState((current) => arrangeCanvasAroundFocus(current)),
      relayout: () => setState((current) => relayoutCanvas(current)),
      clear: () => setState((current) => clearCanvas(current)),
      fitView: () => setState((current) => requestFitCanvasView(current)),
    },
    factsPanel: {
      focusElement: (focusedElement) => setState((current) => focusBrowserElement(current, focusedElement)),
      open: (mode, location) => setState((current) => openFactsPanel(current, mode, location)),
    },
  };
}
